-- Supabase/PostgreSQL support objects for email verification.
-- Run manually if the target database was created before these columns/tables existed.

alter table users
    add column if not exists email_verified boolean default false;

update users
set email_verified = true
where email_verified is null
  and role in ('ADMINISTRATOR', 'DOCTOR');

update users
set email_verified = false
where email_verified is null;

alter table users
    alter column email_verified set default false;

alter table users
    alter column email_verified set not null;

create table if not exists email_verification_tokens (
    id bigint generated by default as identity primary key,
    code_hash varchar(255) not null,
    expiry_date timestamp not null,
    created_at timestamp not null,
    user_id bigint not null unique references users(id) on delete cascade
);

create index if not exists idx_email_verification_tokens_user
    on email_verification_tokens (user_id);
